name: Create Release Notes Pr

on:
  workflow_dispatch:
    inputs:
      last_tag:
        description: 'Previous Tag'
        required: true
      current_tag:
        description: 'Current Tag'
        required: true

jobs:
  build-note-generator:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install dependencies
        run: pip install ruamel.yaml

      - name: Get details from workflow
        run: |
          BASE_BRANCH=${{ github.ref_name }}
          LAST_TAG=${{ github.event.inputs.last_tag }}
          GIT_REPO=${{ github.repository }}
          CURRENT_TAG=${{ github.event.inputs.current_tag }}
          BUILD_NOTES_PR="rc-build-notes-$CURRENT_TAG"
          DATE=$(date -u +"%d-%m-%Y")
          # configure git
          git config --local user.email "tejasrinivas@amagi.com"
          git config --local user.name "tejasrinivask"
          git switch $BASE_BRANCH
          git switch -c $BUILD_NOTES_PR
          # call script for build notes generation
          python ./.github/scripts/create_build_notes.py "$GIT_REPO" "$BASE_BRANCH" "$LAST_TAG" "$CURRENT_TAG" "$DATE"
          # push the changes
          git add build_notes.yaml
          git commit -m "Auto commit"
          git push --set-upstream origin $BUILD_NOTES_PR
          # create pr
          gh pr create -B $BASE_BRANCH -H $BUILD_NOTES_PR --title "Pr for Build Notes of $CURRENT_TAG" --body "TARGET_TAG: $CURRENT_TAG"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
