name: Deploy build notes workflow

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name of format amagimedia/cp-build-automation"
        required: true
      branch_pattern:
        description: "Valid branch patterns for pull request validation"
        required: true

jobs:
  build-note-generator:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Install dependencies
        run: pip install ruamel.yaml

      - name: Push workflow to target repo
        run: |
          TARGET_REPO=${{ github.event.inputs.repo }}
          URL=https://github.com/$TARGET_REPO.git
          git config --global user.email "tejasrinivas@amagi.com"
          git config --global user.name "tejasrinivask"

          mkdir target_repo
          # gh repo clone $URL target_repo
          git clone https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git target_repo

          cd target_repo
          BASE_BRANCH=$(git symbolic-ref --short -q HEAD)
          existed_in_remote=$(git ls-remote --heads origin build-notes-deploy)
          if [[ -z ${existed_in_remote} ]]; then
            git switch -c build-notes-deploy
          else
            git switch build-notes-deploy
            git pull
          fi
          mkdir -p target_repo/.github
          cp -r ../pr_and_build_notes/* .github/
          python .github/scripts/deploy.py "${{ github.event.inputs.branch_pattern }}"
          git add .github/*
          git commit -m "add build notes workflow files"
          git push --set-upstream origin build-notes-deploy
          gh pr create -B $BASE_BRANCH -H build-notes-deploy --title "Add Build Notes workflow" --body "Add build notes workflow files"
        env:
          GH_TOKEN: ${{ secrets.GIT_COLLAB_TOKEN }}
