name: Deploy build notes workflow

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name of format amagimedia/cp-build-automation"
        required: true
      branch_pattern:
        description: "Valid branch patterns for pull request validation"
        required: true

jobs:
  build-note-generator:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Install dependencies
        run: pip install ruamel.yaml

      - name: Get details from workflow
        run: |
          TARGET_REPO=${{ github.event.inputs.repo }}
          URL=https://github.com/$TARGET_REPO.git
          echo $URL
          git config --global user.email "tejasrinivas@amagi.com"
          git config --global user.name "tejasrinivask"
          mkdir target_repo
          gh repo clone $URL target_repo
          mkdir -p target_repo/.github
          cp -r pr_and_build_notes/* target_repo/.github/
          python .github/scripts/deploy.py "${{ github.event.inputs.branch_pattern }}"
          cat target_repo/.github/workflows/pr_body_validator.yaml
          cd target_repo
          BASE_BRANCH=$(git symbolic-ref --short -q HEAD)
          git switch -c build-notes-deploy
          git add .github/*
          git commit -m "add build notes workflow files"
          git config user.name && git config user.email
          git branch
          git push --set-upstream origin build-notes-deploy
          gh pr create -B $BASE_BRANCH -H build-notes-deploy --title "Add Build Notes workflow" --body "Add build notes workflow files"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
